create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  text text not null,
  is_complete boolean default false not null
);

alter table todos enable row level security;

create policy "Allow all access for now"
  on todos for all
  using (true)
  with check (true);
